spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  application:
    name: teammate_backend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teammate
    username: root
    password: 123456
  # session保存时间为一天 存储策略：分布式
  session:
    timeout: 86400
    store-type: redis
  # redis 0号数据库 主机地址：本机
  redis:
    database: 0
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost #设置 cookie 的作用域
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    #当为true时：mybatis-plus会将Java对象的驼峰式命名的常量转成下划线的方式，再与数据库表列字段进行匹配，这样会造成错误。 此时需要利用@TableField注解指定常量在表中的列名。
    #当为false时：不会转，直接对应。
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
