spring:
  profiles:
    active: dev
  application:
    name: user_system_back
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pujun
    username: root
    password: 123456
  # session保存时间为一天 存储策略：分布式
  session:
    timeout: 86400
    store-type: redis
  # redis 0号数据库 主机地址：本机
  redis:
    database: 0
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost #设置 cookie 的作用域
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
